export interface RunEntry {
  w: number; d: string; date: string; phase: string; wt: string;
  type: string; wk: string; mi: number | null; cum: number | null;
}

export const PLAN: RunEntry[] = [
  {w:1,d:'Monday',   date:'Apr 13',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'4 mi easy',                                   mi:4,   cum:4},
  {w:1,d:'Tuesday',  date:'Apr 14',phase:'Base',wt:'Regular', type:'Strides',                wk:'4×strides + 3 mi easy',                       mi:3,   cum:7},
  {w:1,d:'Wednesday',date:'Apr 15',phase:'Base',wt:'Regular', type:'Strength & Conditioning',wk:'Legs: squats, RDL, lunges, calf raises',       mi:null,cum:null},
  {w:1,d:'Thursday', date:'Apr 16',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'3 mi easy',                                   mi:3,   cum:10},
  {w:1,d:'Friday',   date:'Apr 17',phase:'Base',wt:'Regular', type:'Rest',                   wk:'Full rest day',                               mi:null,cum:null},
  {w:1,d:'Saturday', date:'Apr 18',phase:'Base',wt:'Regular', type:'Long Run',               wk:'10 mi easy',                                  mi:10,  cum:20},
  {w:1,d:'Sunday',   date:'Apr 19',phase:'Base',wt:'Regular', type:'Soccer / Cross-Train',   wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:2,d:'Monday',   date:'Apr 20',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'4 mi easy',                                   mi:4,   cum:24},
  {w:2,d:'Tuesday',  date:'Apr 21',phase:'Base',wt:'Regular', type:'Hill Repeats',           wk:'5×hill repeats + 2 mi easy',                  mi:2,   cum:26},
  {w:2,d:'Wednesday',date:'Apr 22',phase:'Base',wt:'Regular', type:'Strength & Conditioning',wk:'Legs: deadlift, step-ups, hip thrust',         mi:null,cum:null},
  {w:2,d:'Thursday', date:'Apr 23',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'3 mi easy',                                   mi:3,   cum:29},
  {w:2,d:'Friday',   date:'Apr 24',phase:'Base',wt:'Regular', type:'Rest',                   wk:'Full rest day',                               mi:null,cum:null},
  {w:2,d:'Saturday', date:'Apr 25',phase:'Base',wt:'Regular', type:'Long Run',               wk:'11 mi easy',                                  mi:11,  cum:40},
  {w:2,d:'Sunday',   date:'Apr 26',phase:'Base',wt:'Regular', type:'Soccer / Cross-Train',   wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:3,d:'Monday',   date:'Apr 27',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'5 mi easy',                                   mi:5,   cum:45},
  {w:3,d:'Tuesday',  date:'Apr 28',phase:'Base',wt:'Regular', type:'Tempo Run',              wk:'2 mi wu + 3 mi tempo + 1 mi cd',              mi:6,   cum:51},
  {w:3,d:'Wednesday',date:'Apr 29',phase:'Base',wt:'Regular', type:'Strength & Conditioning',wk:'Legs: front squat, walking lunges, calf raises',mi:null,cum:null},
  {w:3,d:'Thursday', date:'Apr 30',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'4 mi easy',                                   mi:4,   cum:55},
  {w:3,d:'Friday',   date:'May 01',phase:'Base',wt:'Regular', type:'Rest',                   wk:'Full rest day',                               mi:null,cum:null},
  {w:3,d:'Saturday', date:'May 02',phase:'Base',wt:'Regular', type:'Long Run',               wk:'12 mi easy',                                  mi:12,  cum:67},
  {w:3,d:'Sunday',   date:'May 03',phase:'Base',wt:'Regular', type:'Soccer / Cross-Train',   wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:4,d:'Monday',   date:'May 04',phase:'Base',wt:'Recovery',type:'Easy Run',               wk:'4 mi easy',                                   mi:4,   cum:71},
  {w:4,d:'Tuesday',  date:'May 05',phase:'Base',wt:'Recovery',type:'Strides',                wk:'6×strides + 3 mi easy',                       mi:3,   cum:74},
  {w:4,d:'Wednesday',date:'May 06',phase:'Base',wt:'Recovery',type:'Strength & Conditioning',wk:'Legs (lighter): goblet squat, band work',      mi:null,cum:null},
  {w:4,d:'Thursday', date:'May 07',phase:'Base',wt:'Recovery',type:'Easy Run',               wk:'3 mi easy',                                   mi:3,   cum:77},
  {w:4,d:'Friday',   date:'May 08',phase:'Base',wt:'Recovery',type:'Rest',                   wk:'Full rest day',                               mi:null,cum:null},
  {w:4,d:'Saturday', date:'May 09',phase:'Base',wt:'Recovery',type:'Long Run',               wk:'9 mi easy',                                   mi:9,   cum:86},
  {w:4,d:'Sunday',   date:'May 10',phase:'Base',wt:'Recovery',type:'Soccer / Cross-Train',   wk:'Soccer / light cross-train',                  mi:null,cum:null},
  {w:5,d:'Monday',   date:'May 11',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'5 mi easy',                                   mi:5,   cum:91},
  {w:5,d:'Tuesday',  date:'May 12',phase:'Base',wt:'Regular', type:'Hill Repeats',           wk:'8×hill repeats + 2 mi easy',                  mi:2,   cum:93},
  {w:5,d:'Wednesday',date:'May 13',phase:'Base',wt:'Regular', type:'Strength & Conditioning',wk:'Legs: squat, RDL, split squat',               mi:null,cum:null},
  {w:5,d:'Thursday', date:'May 14',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'4 mi easy',                                   mi:4,   cum:97},
  {w:5,d:'Friday',   date:'May 15',phase:'Base',wt:'Regular', type:'Rest',                   wk:'Full rest day',                               mi:null,cum:null},
  {w:5,d:'Saturday', date:'May 16',phase:'Base',wt:'Regular', type:'Long Run',               wk:'13 mi easy',                                  mi:13,  cum:110},
  {w:5,d:'Sunday',   date:'May 17',phase:'Base',wt:'Regular', type:'Soccer / Cross-Train',   wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:6,d:'Monday',   date:'May 18',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'5 mi easy',                                   mi:5,   cum:115},
  {w:6,d:'Tuesday',  date:'May 19',phase:'Base',wt:'Regular', type:'Tempo Run',              wk:'2 mi wu + 4 mi tempo + 1 mi cd',              mi:7,   cum:122},
  {w:6,d:'Wednesday',date:'May 20',phase:'Base',wt:'Regular', type:'Strength & Conditioning',wk:'Legs: Romanian DL, lunges, calf raises',       mi:null,cum:null},
  {w:6,d:'Thursday', date:'May 21',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'5 mi easy',                                   mi:5,   cum:127},
  {w:6,d:'Friday',   date:'May 22',phase:'Base',wt:'Regular', type:'Rest',                   wk:'Full rest day',                               mi:null,cum:null},
  {w:6,d:'Saturday', date:'May 23',phase:'Base',wt:'Regular', type:'Long Run',               wk:'14 mi easy',                                  mi:14,  cum:141},
  {w:6,d:'Sunday',   date:'May 24',phase:'Base',wt:'Regular', type:'Soccer / Cross-Train',   wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:7,d:'Monday',   date:'May 25',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'6 mi easy',                                   mi:6,   cum:147},
  {w:7,d:'Tuesday',  date:'May 26',phase:'Base',wt:'Regular', type:'Interval',               wk:'6×1 min on / 1 min off',                      mi:3,   cum:150},
  {w:7,d:'Wednesday',date:'May 27',phase:'Base',wt:'Regular', type:'Strength & Conditioning',wk:'Legs: Bulgarian split squat, hip thrust',      mi:null,cum:null},
  {w:7,d:'Thursday', date:'May 28',phase:'Base',wt:'Regular', type:'Easy Run',               wk:'5 mi easy',                                   mi:5,   cum:155},
  {w:7,d:'Friday',   date:'May 29',phase:'Base',wt:'Regular', type:'Rest',                   wk:'Full rest day',                               mi:null,cum:null},
  {w:7,d:'Saturday', date:'May 30',phase:'Base',wt:'Regular', type:'Long Run',               wk:'14 mi easy',                                  mi:14,  cum:169},
  {w:7,d:'Sunday',   date:'May 31',phase:'Base',wt:'Regular', type:'Soccer / Cross-Train',   wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:8,d:'Monday',   date:'Jun 01',phase:'Base',wt:'Recovery',type:'Easy Run',               wk:'4 mi easy',                                   mi:4,   cum:173},
  {w:8,d:'Tuesday',  date:'Jun 02',phase:'Base',wt:'Recovery',type:'Tempo Run',              wk:'2 mi wu + 2 mi tempo + 1 mi cd',              mi:5,   cum:178},
  {w:8,d:'Wednesday',date:'Jun 03',phase:'Base',wt:'Recovery',type:'Strength & Conditioning',wk:'Legs (lighter): goblet squat, band work',      mi:null,cum:null},
  {w:8,d:'Thursday', date:'Jun 04',phase:'Base',wt:'Recovery',type:'Easy Run',               wk:'3 mi easy',                                   mi:3,   cum:181},
  {w:8,d:'Friday',   date:'Jun 05',phase:'Base',wt:'Recovery',type:'Rest',                   wk:'Full rest day',                               mi:null,cum:null},
  {w:8,d:'Saturday', date:'Jun 06',phase:'Base',wt:'Recovery',type:'Long Run',               wk:'10 mi easy',                                  mi:10,  cum:191},
  {w:8,d:'Sunday',   date:'Jun 07',phase:'Base',wt:'Recovery',type:'Soccer / Cross-Train',   wk:'Soccer / light cross-train',                  mi:null,cum:null},
  {w:9,d:'Monday',   date:'Jun 08',phase:'Aerobic',wt:'Regular',type:'Easy Run',             wk:'6 mi easy',                                   mi:6,   cum:197},
  {w:9,d:'Tuesday',  date:'Jun 09',phase:'Aerobic',wt:'Regular',type:'Tempo Run',            wk:'2 mi wu + 5 mi tempo + 1 mi cd',              mi:8,   cum:205},
  {w:9,d:'Wednesday',date:'Jun 10',phase:'Aerobic',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: squat, RDL, step-ups',                mi:null,cum:null},
  {w:9,d:'Thursday', date:'Jun 11',phase:'Aerobic',wt:'Regular',type:'Easy Run',             wk:'5 mi easy',                                   mi:5,   cum:210},
  {w:9,d:'Friday',   date:'Jun 12',phase:'Aerobic',wt:'Regular',type:'Rest',                 wk:'Full rest day',                               mi:null,cum:null},
  {w:9,d:'Saturday', date:'Jun 13',phase:'Aerobic',wt:'Regular',type:'Long Run',             wk:'15 mi easy-moderate',                         mi:15,  cum:225},
  {w:9,d:'Sunday',   date:'Jun 14',phase:'Aerobic',wt:'Regular',type:'Soccer / Cross-Train', wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:10,d:'Monday',   date:'Jun 15',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'6 mi easy',                                   mi:6,   cum:231},
  {w:10,d:'Tuesday',  date:'Jun 16',phase:'Aerobic',wt:'Regular',type:'Hill Repeats',        wk:'10×hill repeats + 2 mi easy',                 mi:2,   cum:233},
  {w:10,d:'Wednesday',date:'Jun 17',phase:'Aerobic',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: deadlift, Bulgarian split squat',    mi:null,cum:null},
  {w:10,d:'Thursday', date:'Jun 18',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'5 mi easy',                                   mi:5,   cum:238},
  {w:10,d:'Friday',   date:'Jun 19',phase:'Aerobic',wt:'Regular',type:'Rest',                wk:'Full rest day',                               mi:null,cum:null},
  {w:10,d:'Saturday', date:'Jun 20',phase:'Aerobic',wt:'Regular',type:'Long Run',            wk:'16 mi easy',                                  mi:16,  cum:254},
  {w:10,d:'Sunday',   date:'Jun 21',phase:'Aerobic',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:11,d:'Monday',   date:'Jun 22',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'6 mi easy',                                   mi:6,   cum:260},
  {w:11,d:'Tuesday',  date:'Jun 23',phase:'Aerobic',wt:'Regular',type:'Interval',            wk:'6×800m at 10K pace',                          mi:3,   cum:263},
  {w:11,d:'Wednesday',date:'Jun 24',phase:'Aerobic',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: front squat, hip thrust, calf',      mi:null,cum:null},
  {w:11,d:'Thursday', date:'Jun 25',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'5 mi easy',                                   mi:5,   cum:268},
  {w:11,d:'Friday',   date:'Jun 26',phase:'Aerobic',wt:'Regular',type:'Rest',                wk:'Full rest day',                               mi:null,cum:null},
  {w:11,d:'Saturday', date:'Jun 27',phase:'Aerobic',wt:'Regular',type:'Long Run',            wk:'16 mi w/ MP miles 12–14',                     mi:16,  cum:284},
  {w:11,d:'Sunday',   date:'Jun 28',phase:'Aerobic',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:12,d:'Monday',   date:'Jun 29',phase:'Aerobic',wt:'Recovery',type:'Easy Run',           wk:'5 mi easy',                                   mi:5,   cum:289},
  {w:12,d:'Tuesday',  date:'Jun 30',phase:'Aerobic',wt:'Recovery',type:'Tempo Run',          wk:'2 mi wu + 3 mi tempo + 1 mi cd',              mi:6,   cum:295},
  {w:12,d:'Wednesday',date:'Jul 01',phase:'Aerobic',wt:'Recovery',type:'Strength & Conditioning',wk:'Legs (lighter)',                          mi:null,cum:null},
  {w:12,d:'Thursday', date:'Jul 02',phase:'Aerobic',wt:'Recovery',type:'Easy Run',           wk:'4 mi easy',                                   mi:4,   cum:299},
  {w:12,d:'Friday',   date:'Jul 03',phase:'Aerobic',wt:'Recovery',type:'Rest',               wk:'Full rest day',                               mi:null,cum:null},
  {w:12,d:'Saturday', date:'Jul 04',phase:'Aerobic',wt:'Recovery',type:'Long Run',           wk:'12 mi easy',                                  mi:12,  cum:311},
  {w:12,d:'Sunday',   date:'Jul 05',phase:'Aerobic',wt:'Recovery',type:'Soccer / Cross-Train',wk:'Soccer / light cross-train',                 mi:null,cum:null},
  {w:13,d:'Monday',   date:'Jul 06',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'7 mi easy',                                   mi:7,   cum:318},
  {w:13,d:'Tuesday',  date:'Jul 07',phase:'Aerobic',wt:'Regular',type:'Tempo Run',           wk:'2 mi wu + 6 mi tempo + 1 mi cd',              mi:9,   cum:327},
  {w:13,d:'Wednesday',date:'Jul 08',phase:'Aerobic',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: squat, split squat, RDL',            mi:null,cum:null},
  {w:13,d:'Thursday', date:'Jul 09',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'5 mi easy',                                   mi:5,   cum:332},
  {w:13,d:'Friday',   date:'Jul 10',phase:'Aerobic',wt:'Regular',type:'Rest',                wk:'Full rest day',                               mi:null,cum:null},
  {w:13,d:'Saturday', date:'Jul 11',phase:'Aerobic',wt:'Regular',type:'Long Run',            wk:'17 mi easy',                                  mi:17,  cum:349},
  {w:13,d:'Sunday',   date:'Jul 12',phase:'Aerobic',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:14,d:'Monday',   date:'Jul 13',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'7 mi easy',                                   mi:7,   cum:356},
  {w:14,d:'Tuesday',  date:'Jul 14',phase:'Aerobic',wt:'Regular',type:'Interval',            wk:'5×1K at 5K–10K effort',                       mi:3,   cum:359},
  {w:14,d:'Wednesday',date:'Jul 15',phase:'Aerobic',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: deadlift, hip thrust, step-ups',     mi:null,cum:null},
  {w:14,d:'Thursday', date:'Jul 16',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'5 mi easy',                                   mi:5,   cum:364},
  {w:14,d:'Friday',   date:'Jul 17',phase:'Aerobic',wt:'Regular',type:'Rest',                wk:'Full rest day',                               mi:null,cum:null},
  {w:14,d:'Saturday', date:'Jul 18',phase:'Aerobic',wt:'Regular',type:'Long Run',            wk:'17 mi w/ MP miles 12–15',                     mi:17,  cum:381},
  {w:14,d:'Sunday',   date:'Jul 19',phase:'Aerobic',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:15,d:'Monday',   date:'Jul 20',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'7 mi easy',                                   mi:7,   cum:388},
  {w:15,d:'Tuesday',  date:'Jul 21',phase:'Aerobic',wt:'Regular',type:'Hill Repeats',        wk:'12×hill repeats + 2 mi easy',                 mi:2,   cum:390},
  {w:15,d:'Wednesday',date:'Jul 22',phase:'Aerobic',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: Bulgarian split squat, calf',        mi:null,cum:null},
  {w:15,d:'Thursday', date:'Jul 23',phase:'Aerobic',wt:'Regular',type:'Easy Run',            wk:'6 mi easy',                                   mi:6,   cum:396},
  {w:15,d:'Friday',   date:'Jul 24',phase:'Aerobic',wt:'Regular',type:'Rest',                wk:'Full rest day',                               mi:null,cum:null},
  {w:15,d:'Saturday', date:'Jul 25',phase:'Aerobic',wt:'Regular',type:'Long Run',            wk:'18 mi easy',                                  mi:18,  cum:414},
  {w:15,d:'Sunday',   date:'Jul 26',phase:'Aerobic',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:16,d:'Monday',   date:'Jul 27',phase:'Aerobic',wt:'Recovery',type:'Easy Run',           wk:'5 mi easy',                                   mi:5,   cum:419},
  {w:16,d:'Tuesday',  date:'Jul 28',phase:'Aerobic',wt:'Recovery',type:'Tempo Run',          wk:'2 mi wu + 3 mi tempo + 1 mi cd',              mi:6,   cum:425},
  {w:16,d:'Wednesday',date:'Jul 29',phase:'Aerobic',wt:'Recovery',type:'Strength & Conditioning',wk:'Legs (lighter)',                          mi:null,cum:null},
  {w:16,d:'Thursday', date:'Jul 30',phase:'Aerobic',wt:'Recovery',type:'Easy Run',           wk:'4 mi easy',                                   mi:4,   cum:429},
  {w:16,d:'Friday',   date:'Jul 31',phase:'Aerobic',wt:'Recovery',type:'Rest',               wk:'Full rest day',                               mi:null,cum:null},
  {w:16,d:'Saturday', date:'Aug 01',phase:'Aerobic',wt:'Recovery',type:'Long Run',           wk:'12 mi easy',                                  mi:12,  cum:441},
  {w:16,d:'Sunday',   date:'Aug 02',phase:'Aerobic',wt:'Recovery',type:'Soccer / Cross-Train',wk:'Soccer / light cross-train',                 mi:null,cum:null},
  {w:17,d:'Monday',   date:'Aug 03',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'7 mi easy',                                   mi:7,   cum:448},
  {w:17,d:'Tuesday',  date:'Aug 04',phase:'Specific',wt:'Regular',type:'Tempo Run',          wk:'2×3 mi at MP w/ 1 mi recovery',               mi:7,   cum:455},
  {w:17,d:'Wednesday',date:'Aug 05',phase:'Specific',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: squat, RDL, hip thrust',            mi:null,cum:null},
  {w:17,d:'Thursday', date:'Aug 06',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'6 mi easy',                                   mi:6,   cum:461},
  {w:17,d:'Friday',   date:'Aug 07',phase:'Specific',wt:'Regular',type:'Rest',               wk:'Full rest day',                               mi:null,cum:null},
  {w:17,d:'Saturday', date:'Aug 08',phase:'Specific',wt:'Regular',type:'Long Run',           wk:'19 mi w/ MP miles 12–17',                     mi:19,  cum:480},
  {w:17,d:'Sunday',   date:'Aug 09',phase:'Specific',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                       mi:null,cum:null},
  {w:18,d:'Monday',   date:'Aug 10',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'8 mi easy',                                   mi:8,   cum:488},
  {w:18,d:'Tuesday',  date:'Aug 11',phase:'Specific',wt:'Regular',type:'Interval',           wk:'6×1K at 10K pace',                            mi:3,   cum:491},
  {w:18,d:'Wednesday',date:'Aug 12',phase:'Specific',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: front squat, step-ups, calf',       mi:null,cum:null},
  {w:18,d:'Thursday', date:'Aug 13',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'6 mi easy',                                   mi:6,   cum:497},
  {w:18,d:'Friday',   date:'Aug 14',phase:'Specific',wt:'Regular',type:'Rest',               wk:'Full rest day',                               mi:null,cum:null},
  {w:18,d:'Saturday', date:'Aug 15',phase:'Specific',wt:'Regular',type:'Long Run',           wk:'20 mi easy',                                  mi:20,  cum:517},
  {w:18,d:'Sunday',   date:'Aug 16',phase:'Specific',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                       mi:null,cum:null},
  {w:19,d:'Monday',   date:'Aug 17',phase:'Specific',wt:'Recovery',type:'Easy Run',          wk:'5 mi easy',                                   mi:5,   cum:522},
  {w:19,d:'Tuesday',  date:'Aug 18',phase:'Specific',wt:'Recovery',type:'Tempo Run',         wk:'2 mi wu + 4 mi tempo + 1 mi cd',              mi:7,   cum:529},
  {w:19,d:'Wednesday',date:'Aug 19',phase:'Specific',wt:'Recovery',type:'Strength & Conditioning',wk:'Legs (moderate): squat, split squat',   mi:null,cum:null},
  {w:19,d:'Thursday', date:'Aug 20',phase:'Specific',wt:'Recovery',type:'Easy Run',          wk:'4 mi easy',                                   mi:4,   cum:533},
  {w:19,d:'Friday',   date:'Aug 21',phase:'Specific',wt:'Recovery',type:'Rest',              wk:'Full rest day',                               mi:null,cum:null},
  {w:19,d:'Saturday', date:'Aug 22',phase:'Specific',wt:'Recovery',type:'Long Run',          wk:'13 mi easy',                                  mi:13,  cum:546},
  {w:19,d:'Sunday',   date:'Aug 23',phase:'Specific',wt:'Recovery',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                      mi:null,cum:null},
  {w:20,d:'Monday',   date:'Aug 24',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'8 mi easy',                                   mi:8,   cum:554},
  {w:20,d:'Tuesday',  date:'Aug 25',phase:'Specific',wt:'Regular',type:'Tempo Run',          wk:'3×2 mi at MP w/ 1 mi recovery',               mi:8,   cum:562},
  {w:20,d:'Wednesday',date:'Aug 26',phase:'Specific',wt:'Regular',type:'Strength & Conditioning',wk:'Legs: squat, RDL, hip thrust, calf',      mi:null,cum:null},
  {w:20,d:'Thursday', date:'Aug 27',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'6 mi easy',                                   mi:6,   cum:568},
  {w:20,d:'Friday',   date:'Aug 28',phase:'Specific',wt:'Regular',type:'Rest',               wk:'Full rest day',                               mi:null,cum:null},
  {w:20,d:'Saturday', date:'Aug 29',phase:'Specific',wt:'Regular',type:'Long Run',           wk:'20 mi w/ MP miles 12–18',                     mi:20,  cum:588},
  {w:20,d:'Sunday',   date:'Aug 30',phase:'Specific',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                       mi:null,cum:null},
  {w:21,d:'Monday',   date:'Aug 31',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'7 mi easy',                                   mi:7,   cum:595},
  {w:21,d:'Tuesday',  date:'Sep 01',phase:'Specific',wt:'Regular',type:'Interval',           wk:'8×800m at 10K pace',                          mi:4,   cum:599},
  {w:21,d:'Wednesday',date:'Sep 02',phase:'Specific',wt:'Regular',type:'Strength & Conditioning',wk:'Legs (lighter): goblet squat, band work', mi:null,cum:null},
  {w:21,d:'Thursday', date:'Sep 03',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'6 mi easy',                                   mi:6,   cum:605},
  {w:21,d:'Friday',   date:'Sep 04',phase:'Specific',wt:'Regular',type:'Rest',               wk:'Full rest day',                               mi:null,cum:null},
  {w:21,d:'Saturday', date:'Sep 05',phase:'Specific',wt:'Regular',type:'Long Run',           wk:'18 mi easy',                                  mi:18,  cum:623},
  {w:21,d:'Sunday',   date:'Sep 06',phase:'Specific',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                       mi:null,cum:null},
  {w:22,d:'Monday',   date:'Sep 07',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'7 mi easy',                                   mi:7,   cum:630},
  {w:22,d:'Tuesday',  date:'Sep 08',phase:'Specific',wt:'Regular',type:'Tempo Run',          wk:'2 mi wu + 5 mi tempo + 1 mi cd',              mi:8,   cum:638},
  {w:22,d:'Wednesday',date:'Sep 09',phase:'Specific',wt:'Regular',type:'Strength & Conditioning',wk:'Legs (moderate)',                         mi:null,cum:null},
  {w:22,d:'Thursday', date:'Sep 10',phase:'Specific',wt:'Regular',type:'Easy Run',           wk:'5 mi easy',                                   mi:5,   cum:643},
  {w:22,d:'Friday',   date:'Sep 11',phase:'Specific',wt:'Regular',type:'Rest',               wk:'Full rest day',                               mi:null,cum:null},
  {w:22,d:'Saturday', date:'Sep 12',phase:'Specific',wt:'Regular',type:'Long Run',           wk:'16 mi w/ MP miles 10–14',                     mi:16,  cum:659},
  {w:22,d:'Sunday',   date:'Sep 13',phase:'Specific',wt:'Regular',type:'Soccer / Cross-Train',wk:'Soccer / cross-train',                       mi:null,cum:null},
  {w:23,d:'Monday',   date:'Sep 14',phase:'Taper',wt:'Regular',type:'Easy Run',              wk:'6 mi easy',                                   mi:6,   cum:665},
  {w:23,d:'Tuesday',  date:'Sep 15',phase:'Taper',wt:'Regular',type:'Tempo Run',             wk:'2 mi wu + 4 mi tempo + 1 mi cd',              mi:7,   cum:672},
  {w:23,d:'Wednesday',date:'Sep 16',phase:'Taper',wt:'Regular',type:'Strength & Conditioning',wk:'Legs (moderate): squat, RDL',               mi:null,cum:null},
  {w:23,d:'Thursday', date:'Sep 17',phase:'Taper',wt:'Regular',type:'Easy Run',              wk:'5 mi easy',                                   mi:5,   cum:677},
  {w:23,d:'Friday',   date:'Sep 18',phase:'Taper',wt:'Regular',type:'Rest',                  wk:'Full rest day',                               mi:null,cum:null},
  {w:23,d:'Saturday', date:'Sep 19',phase:'Taper',wt:'Regular',type:'Long Run',              wk:'14 mi easy',                                  mi:14,  cum:691},
  {w:23,d:'Sunday',   date:'Sep 20',phase:'Taper',wt:'Regular',type:'Soccer / Cross-Train',  wk:'Soccer / cross-train',                        mi:null,cum:null},
  {w:24,d:'Monday',   date:'Sep 21',phase:'Taper',wt:'Regular',type:'Easy Run',              wk:'5 mi easy',                                   mi:5,   cum:696},
  {w:24,d:'Tuesday',  date:'Sep 22',phase:'Taper',wt:'Regular',type:'Tempo Run',             wk:'4×1 mi at MP',                                mi:4,   cum:700},
  {w:24,d:'Wednesday',date:'Sep 23',phase:'Taper',wt:'Regular',type:'Strength & Conditioning',wk:'Legs (light): goblet squat, band work',      mi:null,cum:null},
  {w:24,d:'Thursday', date:'Sep 24',phase:'Taper',wt:'Regular',type:'Easy Run',              wk:'4 mi easy',                                   mi:4,   cum:704},
  {w:24,d:'Friday',   date:'Sep 25',phase:'Taper',wt:'Regular',type:'Rest',                  wk:'Full rest day',                               mi:null,cum:null},
  {w:24,d:'Saturday', date:'Sep 26',phase:'Taper',wt:'Regular',type:'Long Run',              wk:'12 mi easy',                                  mi:12,  cum:716},
  {w:24,d:'Sunday',   date:'Sep 27',phase:'Taper',wt:'Regular',type:'Soccer / Cross-Train',  wk:'Soccer / light cross-train',                  mi:null,cum:null},
  {w:25,d:'Monday',   date:'Sep 28',phase:'Taper',wt:'Regular',type:'Easy Run',              wk:'4 mi easy',                                   mi:4,   cum:720},
  {w:25,d:'Tuesday',  date:'Sep 29',phase:'Taper',wt:'Regular',type:'Tempo Run',             wk:'2 mi wu + 3 mi at MP + 1 mi cd',              mi:6,   cum:726},
  {w:25,d:'Wednesday',date:'Sep 30',phase:'Taper',wt:'Regular',type:'Strength & Conditioning',wk:'Legs (very light): bodyweight only',         mi:null,cum:null},
  {w:25,d:'Thursday', date:'Oct 01',phase:'Taper',wt:'Regular',type:'Easy Run',              wk:'3 mi easy',                                   mi:3,   cum:729},
  {w:25,d:'Friday',   date:'Oct 02',phase:'Taper',wt:'Regular',type:'Rest',                  wk:'Full rest day',                               mi:null,cum:null},
  {w:25,d:'Saturday', date:'Oct 03',phase:'Taper',wt:'Regular',type:'Long Run',              wk:'8 mi easy',                                   mi:8,   cum:737},
  {w:25,d:'Sunday',   date:'Oct 04',phase:'Taper',wt:'Regular',type:'Rest',                  wk:'Short walk or full rest',                     mi:null,cum:null},
  {w:26,d:'Monday',   date:'Oct 05',phase:'Taper',wt:'Regular',type:'Easy Run',              wk:'3 mi easy shakeout',                          mi:3,   cum:740},
  {w:26,d:'Tuesday',  date:'Oct 06',phase:'Taper',wt:'Regular',type:'Strides',               wk:'2 mi w/ 4×strides',                           mi:2,   cum:742},
  {w:26,d:'Wednesday',date:'Oct 07',phase:'Taper',wt:'Regular',type:'Rest',                  wk:'Full rest',                                   mi:null,cum:null},
  {w:26,d:'Thursday', date:'Oct 08',phase:'Taper',wt:'Regular',type:'Shakeout',              wk:'2 mi shakeout',                               mi:2,   cum:744},
  {w:26,d:'Friday',   date:'Oct 09',phase:'Taper',wt:'Regular',type:'Shakeout',              wk:'2 mi shakeout',                               mi:2,   cum:746},
  {w:26,d:'Saturday', date:'Oct 10',phase:'Taper',wt:'Regular',type:'Rest',                  wk:'Full rest',                                   mi:null,cum:null},
  {w:26,d:'Sunday',   date:'Oct 11',phase:'Taper',wt:'Regular',type:'Race',                  wk:'RACE DAY — Long Beach Marathon',              mi:26.2,cum:772.2},
];

export function getTodayStr(): string {
  return new Date().toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

export function getTodayEntry(): RunEntry | null {
  const today = getTodayStr();
  return PLAN.find(e => e.date === today) ?? null;
}

export function getCurrentWeekEntries(): RunEntry[] {
  const today = getTodayEntry();
  if (!today) return [];
  return PLAN.filter(e => e.w === today.w);
}
